import { useEffect, useState } from "react";
import type { Session, User } from "@supabase/supabase-js";
import { supabase } from "@/integrations/supabase/client";

export type Identity = {
  id: string;
  anon_id: string;
  name: string;
  uol_email: string;
  is_admin: boolean;
  is_banned: boolean;
};

/**
 * Ensures the public profile row exists for a confirmed user.
 * The row is created on first authenticated session because the
 * anon handle is generated by the database.
 */
async function ensureProfile(user: User) {
  const { data: existing } = await supabase.rpc("my_identity");
  if (existing && existing.length > 0) return existing[0] as Identity;

  const name = (user.user_metadata?.["full_name"] as string | undefined) ?? "Student";
  await supabase.from("users").insert({
    id: user.id,
    uol_email: user.email ?? "",
    name,
  });

  const { data } = await supabase.rpc("my_identity");
  return (data?.[0] as Identity | undefined) ?? null;
}

export function useAuth() {
  const [session, setSession] = useState<Session | null>(null);
  const [identity, setIdentity] = useState<Identity | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    let active = true;

    const sync = async (nextSession: Session | null) => {
      if (!active) return;
      setSession(nextSession);
      if (!nextSession?.user) {
        setIdentity(null);
        setLoading(false);
        return;
      }
      try {
        const profile = await ensureProfile(nextSession.user);
        if (active) setIdentity(profile);
        if (profile) {
          void supabase
            .from("users")
            .update({ last_seen_at: new Date().toISOString() })
            .eq("id", profile.id);
        }
      } catch {
        if (active) setIdentity(null);
      }
      if (active) setLoading(false);
    };

    const { data: sub } = supabase.auth.onAuthStateChange((_event, nextSession) => {
      void sync(nextSession);
    });

    void supabase.auth.getSession().then(({ data }) => void sync(data.session));

    return () => {
      active = false;
      sub.subscription.unsubscribe();
    };
  }, []);

  return { session, user: session?.user ?? null, identity, loading };
}